version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:8.6
    
    steps:
      - checkout
      - restore_cache:
          name: restore yarn cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      
      - run:
          name: Installing dependencies - Yarn
          command: yarn
      
      - save_cache:
          name: Saving Yarn cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      
      - run:
          name: Linting
          command: yarn lint

      - run:
          name: Setting up Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Testing and Coverage
          command: |
            ./cc-test-reporter before-build
            yarn test:cover
            ./cc-test-reporter after-build --exit-code $?
