version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:8.6
    
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          name: Restore npm cache
          key: dependency-cache-{{ checksum "package.json" }}
      
      - run:
          name: Installing dependencies
          command: npm install
      
      - save_cache:
          name: Saving npm cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      
      - run:
          name: Linting
          command: npm run lint

      - run:
          name: Setting up Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Testing and Coverage
          command: |
            ./cc-test-reporter before-build
            npm run test:cover
            ./cc-test-reporter after-build --exit-code $?
